### PR TITLE
Upgrade Kafka client to 0.10.0.1

### LINKED ISSUE #8: Update app to use 0.10 client
The configuration in the demo app is incompatible with 0.10 and causes hard to diagnose failures.

### PR DESCRIPTION
**Pull request by thody**
Fixes #8

### CODE REVIEW

**Comment by sclasen** [comment]
does this actually work when connecting to a 0.10 cluster?

**Comment by thody** [comment]
@sclasen It's been fine for me, are you seeing something different?

**Comment by sclasen** [comment]
For context, this is exactly what the user was doing when it did not work. They took the code from this repo, and used the 0.10 client dep and it was not working

**Comment by sclasen** [comment]
Testing with SSL?

**Comment by thody** [comment]
Yes, fine with SSL as well.

**Comment by kvlou** [comment]
:+1:

**Comment by kvlou** [comment]
@thody i'm thinking we should keep our project updated with the latest drivers and the default kafka provisioned.

**Comment by thody** [comment]
@kvlou agreed.

**Pull request merged**
